# Generated by Django 5.1.1 on 2026-09-17 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0010_remove_banner_category'),
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_market.color'),
        ),
    ]
